apiVersion: v2
name: geth
description: Helm chart for deploying go-ethereum (geth) execution layer RPC nodes on Kubernetes
type: application
version: 0.1.0
appVersion: "1.14.12"
annotations:
  org.opencontainers.image.source: https://github.com/seokheejang/chain-node-infra
  org.opencontainers.image.licenses: MIT
  org.opencontainers.image.description: go-ethereum (geth) execution layer RPC node for Kubernetes

dependencies:
  - name: common
    version: 0.1.x
    repository: "file://../common"
