apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genesis-generator-private
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/seokheejang/chain-node-infra
      chart: genesis-generator
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/environments/private/genesis-generator.yaml
    - repoURL: https://github.com/seokheejang/chain-node-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ethereum-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
