apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lighthouse-validator-private
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/seokheejang/chain-node-infra.git
    targetRevision: main
    path: charts/lighthouse-validator
    helm:
      valueFiles:
        - ../../environments/private/lighthouse-validator.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ethereum-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
