{{- if and .Values.jwt.enabled (not .Values.jwt.existingSecret) .Values.jwt.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse.fullname" . }}-jwt
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.hex: {{ .Values.jwt.secret | b64enc | quote }}
{{- end }}
