apiVersion: v2
name: genesis-generator
description: Helm chart for generating Ethereum genesis files (EL + CL) for private devnets
type: application
version: 0.1.2
appVersion: "5.3.5"
annotations:
  org.opencontainers.image.source: https://github.com/seokheejang/chain-node-infra
  org.opencontainers.image.licenses: MIT
  org.opencontainers.image.description: Ethereum genesis file generator (EL + CL) for private devnets

dependencies:
  - name: common
    version: 0.1.x
    repository: "oci://ghcr.io/seokheejang/chain-node-infra"
