apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genesis-generator.fullname" . }}-input
  labels:
    {{- include "genesis-generator.labels" . | nindent 4 }}
data:
  values.env: |
    {{- range $key, $value := .Values.chainConfig }}
    {{- if eq $key "GENESIS_TIMESTAMP" }}
    export GENESIS_TIMESTAMP={{ now | unixEpoch | quote }}
    {{- else }}
    export {{ $key }}={{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if .Values.preloadedContracts.enabled }}
    {{- $root := . }}
    {{- $contracts := dict }}
    {{- range .Values.preloadedContracts.contracts }}
    {{- $code := $root.Files.Get .file | trim }}
    {{- $entry := dict "balance" "0" "code" $code "nonce" (.nonce | toString) }}
    {{- $_ := set $contracts (lower .address) $entry }}
    {{- end }}
    export ADDITIONAL_PRELOADED_CONTRACTS={{ $contracts | toJson | quote }}
    {{- end }}
  mnemonics.yaml: |
    {{- .Values.mnemonics | toYaml | nindent 4 }}
