apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
data:
  network: {{ .Values.config.network | quote }}
  sync-mode: {{ .Values.config.syncMode | quote }}
  cache: {{ .Values.config.cache | quote }}
  max-peers: {{ .Values.config.maxPeers | quote }}
